# Generated by Django 2.1.2 on 2018-10-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puppy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasse', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('alter', models.IntegerField(verbose_name=2)),
                ('gewicht', models.IntegerField(verbose_name=2)),
            ],
        ),
    ]
