# Generated by Django 2.1.2 on 2018-11-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date', models.DateTimeField(verbose_name=4)),
                ('UserId', models.IntegerField(verbose_name=8)),
            ],
        ),
    ]
