# Generated by Django 2.1.2 on 2018-11-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='image_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
