# Generated by Django 2.1.3 on 2018-11-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
