# Generated by Django 2.0.9 on 2018-11-27 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_auto_20181102_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='UserId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='totalPrice',
        ),
        migrations.AddField(
            model_name='order',
            name='puppies',
            field=models.ManyToManyField(to='shop.Puppy'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puppy',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='puppy',
            name='description_de',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='puppy',
            name='description_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='puppy',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
